jobs:
  lint-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: |
            flake8 .
          name: Lint
      - run:
          command: |
            python test_hello.py
          name: Test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
orbs:
  python: circleci/python@1.4.0
  heroku: circleci/heroku@1.2.6
version: 2.1
workflows:
  main:
    jobs:
      - lint-test
      - deploy:
          requires:
            - lint-test
          filters:
            branches:
              only: main
